### ISSUE TITLE
v1.0.1 -> v2.0.1.4: Installation Error on Nuget Package 

### ISSUE THREAD

**Issue by OneVideo** [jamesmontemagno/MonoDroidToolkit#13]
"Failed to add reference. The package 'Plugin.CurrentActivity' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.	 "

2018May08: Visual Studio v15.7

**Comment by jamesmontemagno** [comment]
@onovotny these seem to be adding thing as dependencies....

**Comment by onovotny** [comment]
This should be fixed in a later version of the SDK extras; the current version is 1.4.0.

The older version had added some default references to type forwarders that NuGet added as framework references:

https://github.com/onovotny/MSBuildSdkExtras/commit/06d796bd6040c484c1142cf347438be3bac76fc2#diff-06056f08212356b786cf77d7cbcd61f4

Updating to the latest extras should fix this as there's now only a minimal set of default references added and those are not type forwarder facades.

**Comment by jamesmontemagno** [comment]
I have rolled back this updated for now.

**Comment by jamesmontemagno** [comment]
Thanks oren!! <3 I see it pulls in 2 things now:

![image](https://user-images.githubusercontent.com/1676321/39822712-1ba56ea6-5360-11e8-8cb6-4650c1dab473.png)


Does that look correct @onovotny ?
